### ISSUE TITLE
Enhance activation events

### ISSUE THREAD

**Issue by borisblack** [ashenBlade/postgres-dev-helper#1]
**Enhance activation events**
In my project I use the official PostgreSQL repository as a submodule. Therefore, the path to the `src` folder relative to the my project root is `postgresql/src`, so the `PostgreSQL Hacker Helper` extension is not activated. Perhaps it would be better to replace the following entries in the `activationEvents` section:
- `workspaceContains:src/include/nodes/nodes.h` into `workspaceContains:**/src/include/nodes/nodes.h`;
- `workspaceContains:src/include/nodes/nodetags.h` into `workspaceContains:**/src/include/nodes/nodetags.h`.

This would solve such problems.
Thank you!

**Comment by ashenBlade** [comment]
Hi! Thanks for enhancement. I will review activation events in next release.
But now you can fix it just adding (even empty) `pgsql_hacker_helper.json` to your `.vscode` folder.

**Comment by borisblack** [comment]
I got it, thanks!
